name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        wget https://github.com/executablebooks/jupyter-book/archive/refs/tags/v0.13.zip -O jupyter-book.zip
        unzip jupyter-book.zip
        cd jupyter-book-0.13
        python -m build
        cd dist
        pip install jupyter-book-0.13.0.tar.gz

    # Build the book
    - name: Build the book
      run: |
        cd $GITHUB_WORKSPACE
        jupyter-book build ./content

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.JB_TOKEN }}
        publish_dir: ./content/_build/html